- client/src/App.js
- client/src/components/Combo.js
- client/src/components/GetStartedForm.js
`Combo.js` is now a reusable combo box component that wraps `vaadin-combo-box`.
The new `GetStartedForm.js` component includes the combo boxes and the Get Started button.
`App.js` includes `GetStartedForm.js`.
> Refactored combo boxes into reusable component

- client/src/components/GetStartedForm.js
- client/src/import/charities.json
- Changed combo boxes to just County & Charity
- Added Charities JSON file with first 3 charities
> Changed combo boxes to just County & Charity

- client/package.json
- client/src/App.js
- client/src/components/About.js
- client/src/components/Footer.js
- client/src/components/Header.js
- client/src/components/Layout.js
- client/src/index.js
- client/src/pages/About.js
- client/src/pages/Home.js
- client/yarn.lock
Refactored `App` into `Layout`/`Header`/`Footer`/`Home` components
Added React Router
Added About page text
> Initial inner page setup

- client/package.json
- client/public/index.html
- client/src/components/Button.js
- client/src/components/Combo.js
- client/src/components/GetStartedForm.js
- client/src/config.json
- client/yarn.lock
- Added Vaadin button component & styled
- Added Button wrapper component
- Added a config file including the Subbly URL
> Linked Get Started form to Subbly

- client/src/components/Footer.js
- client/src/components/Form/Form.js
- client/src/components/Header.js
- client/src/pages/Home.js
- node_modules/.yarn-integrity
Header - remove nav link ( Home about - contact ) and add new "share" link
Home - edit copy on "form"- section
Footer - add footer content
> add footer

- client/src/assets/styles/main.css
- client/src/components/Form/Form.js
- client/src/pages/Home.js
- client/src/pages/Register.js
> done load metropolis

- client/src/assets/styles/tailwind.css
- client/src/pages/About.js
- client/src/pages/Privacy.js
- client/src/pages/Terms.js
- client/tailwind.config.js
- https://charityshopexchange.com/privacy
- https://charityshopexchange.com/terms
> Add legals text

- client/src/components/ScrollToTop.js
- client/src/index.js
> Pages now automatically scroll to top when visited

- client/src/index.js
> index.js now imports metropolis font

- client/src/components/Footer.js
- client/src/pages/Faq.js
- client/src/pages/Privacy.js
- client/src/pages/Register.js
- client/src/pages/Terms.js
Add FAQ page ( temporary content )
fix footer padding horizontal
styling terms & privacy
> add FAQ (temporary)

- client/src/components/ShareButton.js
> Changed share button to white background, no border

- client/src/components/GetStartedForm.js
> Only show serviced counties in combo for now

- client/public/index.html
- client/src/components/Dialog/index.js
- client/src/components/Dialog/useDialog.js
- client/src/components/ShareButton.js
- client/src/config.json
- Added Facebook fallback for Share button
- Added share properties to config
- Added Open Graph tags to index.html
- Added SEO description & title to index.html
- Extracted generic Dialog component (not used at present)
> Added Facebook fallback for Share button

- client/src/pages/Register.js
- Made register form wider on narrower desktop viewports
- Removed some whitespace above Submit button
- Text tweaks/cleanup
See #37.
> Made register form wider on narrower desktop viewports

- client/src/assets/styles/form.css
- client/src/components/Dialog/useDialog.js
- client/src/components/GetStartedForm.js
- Fixed Tailwind class typo in GetStartedForm
- Added Launching Soon dialog
See #75.
> Added Launching Soon dialog

- client/src/components/Home/GetStartedForm.js
- client/src/components/Home/Hero.js
- client/src/components/Home/HowItWorks.js
- client/src/components/Home/Mission.js
- client/src/components/Home/Subscribe.js
- client/src/pages/Home.js
It was getting long with lots of nested `div`s, making it hard to maintain.
> Refactored Home.js into subcomponents

- client/src/assets/styles/form.css
- client/src/pages/Home.js
> Tweaked Launching Soon dialog styles

- client/src/assets/styles/tailwind.css
- client/src/pages/Faq.js
- client/tailwind.config.js
> Updated FAQ

- client/src/components/Home/GetStartedForm.js
- client/src/components/Home/Hero.js
> Homepage text tweaks to emphasise "UK-wide"

- client/src/components/Form/Form.js
- client/src/components/Home/GetStartedForm.js
- client/src/components/Home/Hero.js
- client/src/components/Home/HowItWorks.js
- client/src/components/Home/Mission.js
- client/src/components/Home/Subscribe.js
- Increased font size of tiny homepage text on mobile
- Adjusted font sizes and section vertical padding for consistency
> Homepage mobile text size & vertical padding adjustments

- client/src/components/Home/Mission.js
- client/src/components/Home/Register.js
- client/src/components/Home/Subscribe.js
- client/src/pages/Home.js
- Added arrows to homepage CTAs
- Reinstated old `Form.js` ("We need more charity shops..." homepage stripe) as `Register.js`
> Added arrows to homepage CTAs

- client/src/components/Home/GetStartedForm.js
- client/src/config.json
- client/src/import/subbly-products.json
- To test, pass `?testMode` as a URL parameter
- Currently only works with Dorset & Hampshire
> Implemented Subbly integration demo

- client/public/index.html
> Fixed up URL to include UID in image filename

- client/src/pages/Register.js
Sets status of form submission, changes button text from Submit  to "Thank you!" - intended to be changed on _Successful_ form submission (yet to be implemented, hard to mock on local server) and redirects after 1 second to homepage.
> setStatus and redirect

- client/public/index.html
- client/src/components/Footer.js
Fixes #143
Added billsby self-service in the footer.
Adding a button beside the current share button doesn't look right. It's taking too much space in the floating area (especially in the mobile view). Maybe we need to readjust the share button or find another place for the `Manage your subscription` button.
> Added billsby self service

- client/src/components/Combo.js
- node_modules/.yarn-integrity
Fix #130 
Can someone please test this on Safari?
> ***I just removed an inline style that hardcoded a white background from the combo box***
> Fix #130 White Background in Combo Box

- .github/CODE_OF_CONDUCT.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE/pull_request.md
- CONTRIBUTING.md
Added misc files such as CONTRIBUTING and PR templates.
Fixes: #138
> Add Misc Files

- src/pages/register.js
Added the following things to fix issue #100 
added email verification to prevent invalid email submissions.
added thank you alert on every successful form submission.
form fields empty about successful form submission.
> Resolve issue #100

- .eslintrc.js
- package.json
- src/components/Home/Checkout/Charity.js
- src/components/Home/Checkout/ContactDetails.js
- src/components/Home/Checkout/DeliveryDetails.js
- src/components/Home/Checkout/Footer.js
- src/components/Home/Checkout/ModalButton.js
- src/components/Home/Checkout/Payment.js
- src/components/Home/Checkout/Selection.js
- src/components/Home/Checkout/index.js
- src/components/Home/Collapsable.js
- src/components/Home/GetStartedForm.js
- src/components/Home/PlanList.js
- src/components/NumberFieldWithLabel.js
- src/hooks/useFormData.js
- src/hooks/usePortal.js
- src/html.js
- src/import/plans-list.json
- src/pages/cookies.js
- src/pages/customer-terms.js
- src/pages/home.js
- src/pages/privacy.js
- src/pages/register.js
- src/pages/terms.js
- yarn.lock
> refactor: convert plan-list data to json format
